default: 
  image: node:latest

build-job:
  stage: build
  script:
    - npm install
  cache:
    key: node-modules
    untracked: true

test:
  stage: test
  script:
    - npm run test
  cache:
    key: node-modules-protected
    policy: pull

desploy-prod:
  stage: deploy
  script:
    - docker build -t mrpeepernumber/nomorexbot .
    - docker push